### ISSUE TITLE
The pico submodule uses ssh reference

### ISSUE THREAD

**Issue by pwoolvett** [raspberrypi/micropython#1]
```console
root@72a5c4e17fe7:~/pico/micropython/lib/pico-sdk# cat .gitmodules 
[submodule "tinyusb"]
        path = lib/tinyusb
        url = git@github.com:raspberrypi/tinyusb.git
        branch = pico
```

(following [1.3 - Building Micropython from source](https://datasheets.raspberrypi.org/pico/sdk/pico_python_sdk.pdf)

**Comment by pwoolvett** [comment]
by "master" you mean the pico branch still, right?

**Comment by kilograham** [comment]
That is exactly what i meant, sorry! (not enough sleep!)
