### ISSUE TITLE
No ujson library included?

### ISSUE THREAD

**Issue by bsatrom** [raspberrypi/micropython#10]
Hi there,

Excited to get my hands on a Pico this week and have been playing around for a few days. I noticed that a few standard Micropython libraries are not included with the default, including ujson. Any plans to support this in an upcoming release?

Thanks!

**Comment by aallan** [comment]
The RP2040 port of MicroPython is currently being merged into the main MicroPython repo, see micropython/micropython#6791. Possibly better to discuss module support there? This repo will be deleted when the changes have been pushed upstream.

**Comment by bsatrom** [comment]
Understood, thanks @aallan!

**Comment by Gadgetoid** [comment]
@bsatrom for the time being you can use our fork with ujson + ure from here - https://github.com/pimoroni/pimoroni-pico/releases

I'm receptive to including additional modules while we wait for the upstream wrinkles to be ironed out.

**Comment by bsatrom** [comment]
Fantastic, thanks @Gadgetoid!
