### ISSUE TITLE
Missing tusb.h file.

### ISSUE THREAD

**Issue by mytechnotalent** [raspberrypi/micropython#11]
When attempting to build:
```
/home/developer/rpi/micropython/ports/rp2/main.c:11:10: fatal error: tusb.h: No such file or directory
   11 | #include "tusb.h"
      |          ^~~~~~~~
```

It does not exist here in the repo.

**Comment by kilograham** [comment]
did you do `git submodule init`?

**Comment by aallan** [comment]
See p 4 and 5 of the [Python SDK](https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-python-sdk.pdf) book.

<img width="840" alt="Screenshot 2021-01-28 at 20 06 40" src="https://user-images.githubusercontent.com/53625/106192654-63b0e400-61a4-11eb-8e21-0359aad7dc63.png">

**Comment by mytechnotalent** [comment]
@kilograham @aallan 
```
MicroPython de1239b6a on 2021-01-28; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>>
```
Thank you much for the help!  I did not see those steps in the guide but this is most helpful!  Is it ok I close the ticket or do you prefer to close?

**Comment by aallan** [comment]
All good! Happy to help!
