### ISSUE TITLE
I2C writes fail sporadically with OS Error 5

### ISSUE THREAD

**Issue by romilly** [raspberrypi/micropython#13]
Multiple I2C writes to an MCP23008 8-bit I/O expander on the Raspberry Pi Pico fail sporadically with OS Error 5.
![Screenshot at 2021-02-13 09-58-06](https://user-images.githubusercontent.com/149310/107847262-02af2000-6de2-11eb-9382-1017ac893c0a.png)

The problem occurs with multiple versions of micropython on the  Pico, including
rp2-pico-20210205-unstable-v1.14-8-g1f800cac3.uf2

Code at https://github.com/romilly/pico-code/blob/master/src/pico_code/pico/mcp23008.py and
https://github.com/romilly/pico-code/blob/master/src/pico_code/pico/mcp3008-demo.py

I am using the I2C pins supported by the Pimoroni Pico explorer base (20 and 21) with its built-in 10K pull-ups, but the same problem arises using pins 0 and 1 with 6K8 pull-ups.

I've seen this behaviour before on the bbc microbit.

**Comment by aallan** [comment]
The RP2040 MicroPython port has now been merged upstream to the main MicroPython repo, see micropython/micropython#6791. Going forward you should report problems with the port  there, https://github.com/micropython/micropython/.
