### ISSUE TITLE
Exposing USB device support

### ISSUE THREAD

**Issue by mcassaniti** [raspberrypi/micropython#5]
Is it possible or a reasonable to ask about exposing USB device support in MicroPython similar to the support for the PyBoard?

Beyond that, is it reasonable to expose even more support so that custom USB devices could be created? For example, a custom U2F token running from MicroPython or an OpenPGP card implementation. I'm sure someone can come up with examples that aren't security related.

**Comment by aallan** [comment]
The RP2040 port of MicroPython is currently being merged into the main MicroPython repo, see micropython/micropython#6791. Possibly better to discuss module support there? This repo will be deleted when the changes have been pushed upstream.
