### ISSUE TITLE
W5500 SPI LAN support

### ISSUE THREAD

**Issue by enesbcs** [raspberrypi/micropython#6]
Is it possible to implement W5500 support for rp2, that is already exists in STM32 micropython port?

https://github.com/raspberrypi/micropython/blob/pico/ports/stm32/modnwwiznet5k.c

**Comment by aallan** [comment]
The RP2040 port of MicroPython is currently being merged into the main MicroPython repo, see micropython/micropython#6791. Possibly better to discuss module support there? This repo will be deleted when the changes have been pushed upstream.
