### ISSUE TITLE
machine.RTC support

### ISSUE THREAD

**Issue by RabAusten** [raspberrypi/micropython#7]
I'm requesting inclusion of the RTC module, as it cannot currently be imported from _machine_. I would like to be able to set and read from the Pico's onboard RTC, to support time accurate operations.

One of the key features of Pico that caught my attention was the RTC and IRQ wake, so you could have the option to sleep the device to ultra low power consumption and then wake it at accurate time intervals to perform operations, before sleeping once more. I strongly believe this should be supported in Micropython, if at all possible.

https://docs.micropython.org/en/latest/library/machine.RTC.html

https://github.com/raspberrypi/pico-sdk/tree/26653ea81e340cacee55025d110c3e014a252a87/src/rp2_common/hardware_rtc

https://github.com/raspberrypi/pico-examples/blob/master/rtc/hello_rtc/hello_rtc.c

**Comment by cjohnson-phys** [comment]
I agree that this feature would be useful

**Comment by DWiskow** [comment]
Ditto, it seems to be a missing item in the Pico implementation

**Comment by aallan** [comment]
While `machine.RTC` doesn't yet exist, but the time module uses the internal RTC to get its date/time.

**Comment by petedyerarm** [comment]
> While `machine.RTC` doesn't yet exist, but the time module uses the internal RTC to get its date/time.
Yes - it is possible to get the date/time, but not to set the RTC to the current time. Or at least I couldn't find an interface to allow this.

**Comment by RabAusten** [comment]
> > While `machine.RTC` doesn't yet exist, but the time module uses the internal RTC to get its date/time.
> 
> Yes - it is possible to get the date/time, but not to set the RTC to the current time. Or at least I couldn't find an interface to allow this.

Exactly, using _time_ is ok if you only want relative times (e.g. 1 hour from now or repeat something every 10 minutes), but you need to be able to set the RTC to exact time if your application needs to function at specific date/time.

**Comment by petedyerarm** [comment]
I worked around it with the following, but it shouldn't be necessary. I've put in here in case it helps anybody.

```
# Workaround for the fact the RTC cannot be set.
# time_at_start comes from https://www.unixtimestamp.com/
time_at_start = 1611651000
time_delta = time_at_start - utime.time()
```

`now = utime.localtime(utime.time() + time_delta)
`

**Comment by RabAusten** [comment]
> I worked around it with the following, but it shouldn't be necessary. I've put in here in case it helps anybody.
> 
> ```
> # Workaround for the fact the RTC cannot be set.
> # time_at_start comes from https://www.unixtimestamp.com/
> time_at_start = 1611651000
> time_delta = time_at_start - utime.time()
> ```
> 
> `now = utime.localtime(utime.time() + time_delta) `

Useful, thanks. This is a good workaround for using time, however this has reminded me I need to be more specific in the OP, as I would like full support of RTC, which also includes setting alarms and waking the device from sleep. The potential to sleep the device into a very low power state and then wake it again at accurate time intervals is very important for a lot of applications. I'll edit the OP, to that fact. Thank you.

**Comment by aallan** [comment]
The RP2040 port of MicroPython is currently being merged into the main MicroPython repo, see micropython/micropython#6791. Possibly better to discuss module support there? This repo will be deleted when the changes have been pushed upstream.
