### ISSUE TITLE
Gpio input pins default to floating

### ISSUE THREAD

**Issue by NormanDunbar** [raspberrypi/micropython#8]
The "Getting Started with MicroPython" shows examples of how to read a button in Chapter 5.

The button is created as `button = machine.Pin(16, machine.Pin.IN)` however, testing shows weird operations and investigation implies that the default pull down is not being applied and the pin is being left floating, not pulled down -- it triggers a press if I move my hand near the jumper wire.

The C SDK equivalent code `gpio_set_dir(nn, GPIO_IN)` does appear to enable pull down as there is no floating problem.

I suspect the MicroPython code might not be setting the pull down?

Cheers,
Norm.

**Comment by aallan** [comment]
At power up MicroPython does not touch any GPIO state of the hardware, so pins should be in whatever state they start in.

If the user constructs a Pin object without specifying any mode/pull/etc arguments (just the pin id) then it leaves the pin alone.  Eg machine.Pin(1) won't reconfigure anything.

If the user constructs a Pin object by specifying the mode (eg IN, OUT) but don't specify any pull, then it defaults to setting the pin to "no pull" mode (ie disables pull up and pull down).

If the user constructs a Pin object by specifying the mode and the pull then it configures the pin as requested.

**Comment by lurch** [comment]
Note that this isn't entirely dissimilar to the behaviour of the RPi.GPIO library, which many Raspberry Pi users will be familiar with - that also defaults to floating input unless a pull-direction is explicitly given https://sourceforge.net/p/raspberry-gpio-python/wiki/Inputs/

**Comment by NormanDunbar** [comment]
Hi @aallan,

Thanks for the info. I'm sure I read the under MicroPython, the pins default to pull down -- maybe I dreamt it.

The C SDK certainly seems to enable pull down as the same circuit (3v3 -> switch -> gpio14) works perfectly and no floating pin problems.

Thanks again.

Cheers,
Norm.
