### ISSUE TITLE
Different machine.Pin API compared to normal MicroPython?

### ISSUE THREAD

**Issue by kiwih** [raspberrypi/micropython#9]
Hello,

I'm not sure if this is deliberate or not but MicroPython on the Raspberry Pi Pico has a different API for the Pin class than normal MicroPython. The normal API is at https://docs.micropython.org/en/latest/library/machine.Pin.html - note the methods `mode()`, `pull()`, `on()`, and `off()`.
For some reason, on the Pico these functions have been replaced:
* `init()` replaces both `mode()` and `pull()`,
* `high()` replaces `on()`
* `low()` replaces `off()`

This immediately tripped me up when writing some code for the Pico. I can't see a good reason for this change, but it seems deliberate from inspecting the source of your MicroPython port (the comments match the new function names, at least). What was the reason for the change? Are you concerned that this will cause compatibility issues with code written for other devices?

**Comment by aallan** [comment]
The RP2040 port was done by @dpgeorge, so my guess the change was intentional.

**Comment by kiwih** [comment]
I guess I have two concerns,
* Ecosystem fragmentation
* Documentation: Nowhere in the [Python SDK document](https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-python-sdk.pdf) does it mention this change, and as the Pico is so new when you google 'machine Pin MicroPython Pico' it still leads you to the official API. I was utterly confused until I thought to actually look in the source code of the RP2040 MicroPython implementation.

**Comment by lurch** [comment]
FYI @kiwih in case you're not aware: @dpgeorge is the original creator of MicroPython, so it's safe to assume he knows what he's doing?

**Comment by kiwih** [comment]
That's fair, although I'd still be interested to know what the rationale for the change is

**Comment by ghollingworth** [comment]
It would be better to have this discussion on the official site...

https://github.com/micropython/micropython/pull/6791

**Comment by tannewt** [comment]
> I guess I have two concerns,
> 
>   * Ecosystem fragmentation
> 
>   * Documentation: Nowhere in the [Python SDK document](https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-python-sdk.pdf) does it mention this change, and as the Pico is so new when you google 'machine Pin MicroPython Pico' it still leads you to the official API. I was utterly confused until I thought to actually look in the source code of the RP2040 MicroPython implementation.

@kiwih Please check out CircuitPython. We've factored the Python -> C layer out of each port (into shared-bindings) for exactly this reason. It makes the APIs identical across ports and by extension libraries and examples. 

UF2 is here: https://circuitpython.org/board/raspberry_pi_pico/
API docs are here: https://circuitpython.readthedocs.io/en/latest/shared-bindings/index.html

**Comment by kiwih** [comment]
Actually I was just looking at CircuitPython (discovered it via earlier googling) - I actually already installed the beta `.uf2` and gave it a go. It looks quite different from MicroPython, which is a shame, since the otherwise-lovely raspberry pi SDK docs don't really match CircuitPython very well. Ah well, "Python" and "ecosystem fragmentation", name a more iconic duo.

**Comment by tannewt** [comment]
There is a lot of existing CircuitPython docs and tutorials that should "just work" on the RP2040. The only thing we need to document is the PIO. Everything else is the same.

Workflow/getting started is covered here: https://learn.adafruit.com/welcome-to-circuitpython
API essentials here: https://learn.adafruit.com/circuitpython-essentials
API reference (including `rp2pio` for PIO) here: https://circuitpython.readthedocs.io/en/latest/README.html
